export const GET_DOCTORS = 'GET_DOCTORS';
export const UPDATE_SELECTED_DOCTOR = 'UPDATE_SELECTED_DOCTOR';
export const UPDATE_SELECTED_DATE = 'UPDATE_SELECTED_DATE';
export const FETCH_SLOTS_SUCCESS=  'FETCH_SLOTS_SUCCESS'
export const FETCH_SLOTS_ERROR=  'FETCH_SLOTS_ERROR'
export const SELECT_SLOT_TIME=  'SELECT_SLOT_TIME'
export const SET_APPOINTMENT_DETAILS = "SET_APPOINTMENT_DETAILS";
export const CANCEL_APPOINTMENT = "CANCEL_APPOINTMENT";
export const APPOINTMENTS_SUCCESS = "APPOINTMENTS_SUCCESS";
export const APPOINTMENTS_FAIL = "APPOINTMENTS_FAIL";



  